#!/usr/bin/env python

from importlib import import_module
import argparse 

all_models = ["dpa", "dea", "psmc", "acisfp", "fep1_mong",
              "fep1_actel", "bep_pcb"]

parser = argparse.ArgumentParser()
parser.add_argument('--models', type=str)
parser.add_argument('args', nargs=argparse.REMAINDER)

args = parser.parse_args()

if args.models is None:
    models = all_models
else:
    models = args.which_models.split(",")

for model in models:
    model_check = import_module("{}_check".format(model))
    model_check.test(args.args)
