name: Python ruff check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Lint with ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    # Include `--format=github` to enable automatic inline annotations.
    - name: Run Ruff
      run: ruff --format=github .
